### PR TITLE
Add greenness reports Q1 and Q2

### PR DESCRIPTION
**Pull request by Blast545**
I think the reports should be categorized by "report_name/year/report_name_with_date", this PR should reflect this.

Other than that, the reports were generated using internal tools, with:

`python3 reports/greenness_report.py -f "2024-01-01" -u "2024-02-01"`
`python3 reports/greenness_report.py -f "2024-02-01" -u "2024-03-01"`
`python3 reports/greenness_report.py -f "2024-03-01" -u "2024-04-01"`

### CODE REVIEW

**Review by Crola1702 — COMMENTED** [review]
My question here is: 

Is this something we want to store in the repository? If these are not versioned nor modified, I don't see a reason to add them to the repo code. Maybe as a [GitHub discussion item](https://github.com/osrf/buildfarm-tools/discussions) of in a [GitHub Wiki](https://github.com/osrf/buildfarm-tools/wiki)?

**Comment by Blast545** [comment]
Second commit:

`python3 greenness_report.py -f "2024-04-01" -u "2024-05-01"`
`python3 greenness_report.py -f "2024-05-01" -u "2024-06-01"`
`python3 greenness_report.py -f "2024-06-01" -u "2024-07-01"`

**Comment by Blast545** [comment]
@Crola1702 Github discussions nor github wikis support .html files. Best thing we can do for now is upload them as code, and then setting up github pages to access them as rendered pages.

**Review by Crola1702 — APPROVED** [review]
Do we have plans to add different types of reports to `reports/` directory, besides greenes reports?

**Comment by Blast545** [comment]
@Crola1702 On top of my mind, I would like to see a monthly report of disabled tests by the buildfarm and known issues. 

Those might not even end up being generated reports, but for now let's keep the folder structure with the greenness reports in case we proceed to add more later.

**Pull request merged**
